class myNewClass:
    'This is my python class'
    a = 10                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
    def func(self):
        print('hello go to sleep now.')

#print(myNewClass.a)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
#print(myNewClass.func)
#print(myNewClass.__doc__)

#creating an object
ob = myNewClass()
#This means to say, since MyClass.func is a function object (attribute of class), ob.func will be a method object.
print(myNewClass.func)
print(ob.func)
ob.func()                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       